apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: registrycap1.azurecr.io/my-node-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: CONFIG_KEY
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: CONFIG_KEY
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: API_KEY
